name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  in_decoker_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run mvn clean
        run: mvn clean

      - name: Run mvn package
        run: mvn package

      - name: Login container registry
        env:
          HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      - name: Push container registry
        env:
          HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

      - name: Realise container registry
        env:
          HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:realise -a ${{ secrets.HEROKU_APP_NAME }} web
